### ISSUE TITLE
Broken with fish 3.4.0

### ISSUE THREAD

**Issue by PhML** [oh-my-fish/plugin-virtualfish#5]
Since update to fish 3.4.0 `set -q` behavior changed: https://fishshell.com/docs/3.4/relnotes.html

Seems that:

```fish
if set -q $VIRTUALFISH_PYTHON
```
should be replaced by:

```fish
if not set -q $VIRTUALFISH_PYTHON; or set -q $VIRTUALFISH_PYTHON
```

**Comment by denniswebb** [comment]
A quick fix is to run `sed -i '' '1 s/^.*$/if not set -q VIRTUALFISH_PYTHON/' ~/.local/share/omf/pkg/virtualfish/conf.d/virtualfish.fish` which will replace this line for you.

Edit: fixed incorrect logic
